### PR TITLE
fix(sdk/react): declare @base-ui/react and @lezer/highlight as devDependencies

### LINKED ISSUE #1044: bug: @stigmer/react's optional peers @base-ui/react and @lezer/highlight are missing from its devDependencies; the clean-room typecheck is red on main
## What happened

`ci.ts-sdk`'s `typecheck (clean-room resolution)` job has been red on `main` for its last three pushes (runs 34444426519, 34460342474, 34464307428):

```
sdk/react/src/composer/ConfigureMenu.tsx(4,25): error TS2307: Cannot find module '@base-ui/react/popover' or its corresponding type declarations.
sdk/react/src/internal/menu.tsx(4,39): error TS2307: Cannot find module '@base-ui/react/menu' or its corresponding type declarations.
sdk/react/src/internal/tooltip.tsx(4,45): error TS2307: Cannot find module '@base-ui/react/tooltip' or its corresponding type declarations.
```

It is not an upstream break: `@base-ui/react@1.8.0` (what a fresh caret resolve picks) still exports every one of those subpaths. The package is simply not resolvable from `sdk/react` when the workspace is installed fresh.

`@stigmer/react` imports `@base-ui/react` in nine source files and `@lezer/highlight` in one (`manifest/YamlEditor.tsx`), and declares both as optional peers, but lists neither in its own `devDependencies`. Its other thirteen optional peers (every `@codemirror/*`, `@tanstack/react-table`, `@xyflow/react`, `elkjs`, `mermaid`, `react-virtuoso`, `recharts`) all do appear in `devDependencies`. Today the two resolve only because sibling workspaces (`client-apps/web`, `client-apps/desktop`, the codemirror packages) happen to pull them into the root `node_modules`; on `main` at `400dda220`, `node_modules/@base-ui/react` exists at the root and `sdk/react/node_modules/@base-ui` does not.

## What I expected

`sdk/react` typechecks and builds on its own declared dependencies, without relying on what its sibling workspaces happen to install. The clean-room job is green on `main`.

## Steps to reproduce

1. Fresh clone of `main`, Node 22 (`.nvmrc`).
2. `corepack enable && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install` (the clean-room job's install, lockfile-free).
3. `yarn workspace @stigmer/protos run build && npx tsc -p sdk/react/tsconfig.build.json --noEmit`.
4. Every `@base-ui/react/*` import fails with TS2307.

## Context

Found while preparing the Stage B (Turborepo adoption) work of stigmer-cloud project `20260904.04`, which moves this job off yarn. Under npm's fresh resolution the job would go green by hoisting rather than by correctness, which is why this is filed on its own before that change lands.

### PR DESCRIPTION
**Pull request by whysosuresh**
## Summary
Adds `@base-ui/react` and `@lezer/highlight` to `@stigmer/react`'s `devDependencies`, the pattern its other thirteen optional peers already follow. Two lines; no resolved version changes.

## Context
`ci.ts-sdk`'s `typecheck (clean-room resolution)` job has been red on `main` since run 34444426519 with `TS2307: Cannot find module '@base-ui/react/popover'` (and `/menu`, `/tooltip`). Not an upstream break: `@base-ui/react@1.8.0` still exports every subpath. `sdk/react` imports the package in nine modules (and `@lezer/highlight` in `manifest/YamlEditor.tsx`) and declares both as optional peers, but listed neither in its own `devDependencies`. They resolved for `sdk/react` only because sibling workspaces happen to hoist them to the root `node_modules`; yarn's lockfile-free install did not, and the typecheck told the truth. The clean-room job caught a real declaration gap.

Found while preparing Stage B of stigmer-cloud project `20260904.04` (Turborepo adoption), which moves that job from yarn to npm. Under npm's hoisting the job would have gone green for the wrong reason, so this lands on its own first.

## Changes
- `sdk/react/package.json`: `@base-ui/react` `^1.3.0` and `@lezer/highlight` `^1.2.3` added to `devDependencies` (ranges as the file does it: at or above the peer floor, caret on a recent minor).
- `package-lock.json`: `@lezer/highlight` and `@lezer/common` flip from `devOptional` to `dev`; nothing else moves.

## Implementation notes
- Both packages were already resolved at exactly these versions in the lockfile, so `npm ci` trees are byte-identical before and after.
- The optional-peer *design* question (nine top-level imports of a peer documented as optional) is separate and not touched here.

## Breaking changes
- None.

## Test plan
- Locally (Node 22.22.1, npm 10.9.4): `npm install` → only the two declarations and two lock flags change; `npm ls @base-ui/react @lezer/highlight -w @stigmer/react` shows both declared; `npm run build -w @stigmer/protos && npx tsc -p sdk/react/tsconfig.build.json --noEmit` green.
- On this PR: `ci.ts-sdk` `typecheck (clean-room resolution)` is the proof; it is the job that has been red on `main`.

## Risks
- None beyond a lockfile flag flip. Rollback is a revert.

## Checklist
- [x] Docs updated (not needed)
- [x] Tests added/updated (the clean-room CI job is the test)
- [x] Backward compatible

Closes #1044

### CODE REVIEW

**Comment by whysosuresh** [comment]
Lanes: 14 of 15 green including both `ci.ts-sdk` jobs; the one red is `ci.docs` SDK Docs Freshness, pre-existing on `main` (`docs/cli/commands/up.mdx` needs `make gen-cli-docs`, drift from #1035; this PR trips it by touching `sdk/react/**`). Not this PR's content.
