### ISSUE TITLE
bug: @stigmer/react's optional peers @base-ui/react and @lezer/highlight are missing from its devDependencies; the clean-room typecheck is red on main

### ISSUE THREAD

**Issue by whysosuresh** [stigmer/stigmer#1044]
## What happened

`ci.ts-sdk`'s `typecheck (clean-room resolution)` job has been red on `main` for its last three pushes (runs 34444426519, 34460342474, 34464307428):

```
sdk/react/src/composer/ConfigureMenu.tsx(4,25): error TS2307: Cannot find module '@base-ui/react/popover' or its corresponding type declarations.
sdk/react/src/internal/menu.tsx(4,39): error TS2307: Cannot find module '@base-ui/react/menu' or its corresponding type declarations.
sdk/react/src/internal/tooltip.tsx(4,45): error TS2307: Cannot find module '@base-ui/react/tooltip' or its corresponding type declarations.
```

It is not an upstream break: `@base-ui/react@1.8.0` (what a fresh caret resolve picks) still exports every one of those subpaths. The package is simply not resolvable from `sdk/react` when the workspace is installed fresh.

`@stigmer/react` imports `@base-ui/react` in nine source files and `@lezer/highlight` in one (`manifest/YamlEditor.tsx`), and declares both as optional peers, but lists neither in its own `devDependencies`. Its other thirteen optional peers (every `@codemirror/*`, `@tanstack/react-table`, `@xyflow/react`, `elkjs`, `mermaid`, `react-virtuoso`, `recharts`) all do appear in `devDependencies`. Today the two resolve only because sibling workspaces (`client-apps/web`, `client-apps/desktop`, the codemirror packages) happen to pull them into the root `node_modules`; on `main` at `400dda220`, `node_modules/@base-ui/react` exists at the root and `sdk/react/node_modules/@base-ui` does not.

## What I expected

`sdk/react` typechecks and builds on its own declared dependencies, without relying on what its sibling workspaces happen to install. The clean-room job is green on `main`.

## Steps to reproduce

1. Fresh clone of `main`, Node 22 (`.nvmrc`).
2. `corepack enable && YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install` (the clean-room job's install, lockfile-free).
3. `yarn workspace @stigmer/protos run build && npx tsc -p sdk/react/tsconfig.build.json --noEmit`.
4. Every `@base-ui/react/*` import fails with TS2307.

## Context

Found while preparing the Stage B (Turborepo adoption) work of stigmer-cloud project `20260904.04`, which moves this job off yarn. Under npm's fresh resolution the job would go green by hoisting rather than by correctness, which is why this is filed on its own before that change lands.

**Comment by whysosuresh** [comment]
Fixed in #1045 — leaving this open; it will **close automatically when #1045 merges to `main`**, and ships in the next Stigmer release.

### What's fixed
- `sdk/react/package.json`: `@base-ui/react` (`^1.3.0`) and `@lezer/highlight` (`^1.2.3`) are now in `@stigmer/react`'s `devDependencies`, the pattern its other thirteen optional peers already follow. Both were already resolved at exactly those versions, so the lockfile change is two `dev` flags and nothing else moves.
- Proof on the PR: `ci.ts-sdk` `typecheck (clean-room resolution)`, the job that had been red on `main` for three pushes, is green on #1045.

One lane on #1045 is red for a pre-existing reason unrelated to this change: `ci.docs` SDK Docs Freshness reports `CLI docs are stale — run 'make gen-cli-docs'` (`docs/cli/commands/up.mdx`, drift from #1035, already on `main`; it fails any PR that touches `sdk/react/**`).

Found while preparing the move of that clean-room job from yarn to npm (stigmer-cloud project 20260904.04, Stage B). npm hoists sibling workspaces' dependencies to the root, so under npm the job would have gone green without this fix, for the wrong reason. The yarn job's last catch was a real one.
